version: '3'
services:
  ranger:
    image: kmor76/ranger:2.5.0
    container_name: ranger
    hostname: ranger.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "6080:6080"
    depends_on:
      ranger-zk:
        condition: service_started
      ranger-db:
        condition: service_healthy
      ranger-solr:
        condition: service_started
    environment:
      - RANGER_VERSION
      - RANGER_DB_TYPE
      - DEBUG_ADMIN=${DEBUG_ADMIN:-false}
    command:
      - /home/ranger/scripts/ranger.sh

  ranger-zk:
    image: kmor76/ranger-zk:2.5.0
    container_name: ranger-zk
    hostname: ranger-zk.example.com
    networks:
      - ranger
    ports:
      - "2181:2181"

  ranger-solr:
    image: kmor76/ranger-solr:2.5.0
    container_name: ranger-solr
    hostname: ranger-solr.example.com
    networks:
      - ranger
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits/

  ranger-db:
    image: kmor76/ranger-postgres:2.5.0
    container_name: ranger-postgres
    hostname: ranger-db.example.com
    networks:
      - ranger
    healthcheck:
      test: 'su -c "pg_isready -q" postgres'
      interval: 10s
      timeout: 2s
      retries: 30

networks:
  ranger:
    name: rangernw
